'use client'
import Image from 'next/image'
import React, { useState } from 'react'

type Tab = 'students' | 'educators' | 'bloggers'

interface TabContent {
    title: string
    heading: string
    subheading: string
    description: string
    features: string[]
    image: string
    icon: React.ReactNode
}

const StudentIcon = () => (
    <Image src='/assets/student-icon.png' alt='student-icon' width={48} height={48} />
)

const EducatorIcon = () => (
    <Image src='/assets/educators-icon.png' alt='student-icon' width={48} height={48} />
)

const BloggerIcon = () => (
    <Image src='/assets/bloggers-icon.png' alt='blogger-icon' width={48} height={48} />
)

const OurAIDetectorIsPerfectFor = () => {
    const [activeTab, setActiveTab] = useState<Tab>('students')

    const tabContent: Record<Tab, TabContent> = {
        students: {
            title: 'Students',
            heading: 'STUDENTS',
            subheading: 'Confidently submit your papers',
            description: "Scribbr's AI Detector helps ensure that your essays and papers adhere to your university guidelines.",
            features: [
                'Verify the authenticity of your sources, ensuring that you only present trustworthy information.',
                'Identify any AI-generated content, like that created by ChatGPT, that might need proper attribution.',
                'Analyze content in English, German, French, and Spanish.'
            ],
            image: '/assets/student.png',
            icon: <StudentIcon />
        },
        educators: {
            title: 'Educators',
            heading: 'EDUCATORS',
            subheading: 'Ensure academic integrity',
            description: 'Help your students maintain academic honesty while embracing new technology responsibly.',
            features: [
                'Detect AI-generated content in student submissions',
                'Promote proper citation and attribution practices',
                'Support multiple languages for international programs'
            ],
            image: '/assets/student.png',
            icon: <EducatorIcon />
        },
        bloggers: {
            title: 'Bloggers',
            heading: 'BLOGGERS',
            subheading: 'Maintain authentic content',
            description: 'Ensure your blog content remains genuine and builds trust with your audience.',
            features: [
                'Verify content originality',
                'Detect AI-generated sections',
                'Maintain your unique voice'
            ],
            image: '/assets/student.png',
            icon: <BloggerIcon />
        }
    }
    return (
        <div className='w-full'>
            {/* AI Detector for ChatGPT, Copilot, Gemini, and more */}
            <div className='bg-[#F6F6F6] w-full'>
                <div className='max-w-[1324px] mx-auto w-full px-3.5 sm:px-5 py-10 sm:py-16 md:py-24 flex items-center lg:flex-row flex-col justify-between gap-7 sm:gap-10'>
                    <div className='lg:w-1/2'>
                        <Image src='/assets/ai-detector-for-chatgpt-copilot-gemini.png' alt='ai-detector-for-chatgpt-copilot-gemini' width={645} height={392} />
                    </div>
                    <div className='lg:w-1/2'>
                        <h1 className='text-[#202F66] text-[24px] sm:text-[30px] md:text-[36px] md:leading-[46px] font-bold tracking-[-0.04em] uppercase'>AI Detector for ChatGPT, Copilot, Gemini, and more</h1>
                        <p className='mt-1.5 sm:mt-3 mb-1.5 sm:mb-2.5 text-[#333333] text-sm sm:text-[16px] leading-[22px] sm:leading-[28px] font-normal tracking-[-0.03em]'>Scribbr's AI Detector accurately detects texts generated by the most popular tools, like ChatGPT, Gemini, and Copilot. It also offers advanced features, such as differentiation between human-written, AI-generated, and AI-refined content and paragraph-level feedback for more detailed analysis of your writing.</p>
                        <p className='text-[#333333] text-sm sm:text-[16px] leading-[22px] sm:leading-[28px] font-normal tracking-[-0.03em]'>Our advanced AI checker tool can detect the latest models, like GPT4 with high accuracy. Note that no AI Detector can provide complete accuracy (see our research). As language models continue to develop, detection tools will always have to race to keep up with them.</p>
                    </div>
                </div>
            </div>

            {/* Our AI Detector is perfect for.. */}
            <div className='bg-[#E2E9F1]'>
                <div className='max-w-[1324px] mx-auto w-full px-3.5 sm:px-5 py-12 md:py-20'>
                    <h1 className='text-center text-[#1B243C] text-[25px] sm:text-[30px] md:text-[40px] font-extrabold uppercase'>Our AI Detector is perfect for..</h1>
                    {/* Tabs */}
                    <div className="mt-12 flex justify-center gap-2 sm:gap-4 mb-10 sm:mb-12">
                        {(Object.keys(tabContent) as Tab[]).map((tab) => (
                            <button
                                key={tab}
                                onClick={() => setActiveTab(tab)}
                                className={`border border-[#00000026] pt-2.5 pb-4 flex flex-col items-center rounded-lg px-2 w-full sm:w-[278px] transition-all duration-300 transform
                                ${activeTab === tab
                                        ? 'bg-main-clr text-white scale-105'
                                        : 'bg-white text-[#1B243C] hover:bg-slate-50'}`}
                            >
                                <div className="sm:w-12 sm:h-12 w-9 h-9 rounded-full bg-gray-200 mb-3 overflow-hidden flex items-center justify-center">
                                    {tabContent[tab].icon}
                                </div>
                                <span className="text-base sm:text-[20px] font-bold">{tabContent[tab].title}</span>
                            </button>
                        ))}
                    </div>

                    {/* Content */}
                    <div className="grid md:grid-cols-2 gap-4 sm:gap-8 items-center">
                        <div className="space-y-4 sm:space-y-6">
                            <h2 className="text-[26px] sm:text-[36px] leading-[30px] font-bold text-[#151515] font-helvetica">
                                {tabContent[activeTab].heading}
                            </h2>
                            <h3 className="text-[20px] sm:text-[24px] font-bold text-[#151515E5] leading-[24px]">
                                {tabContent[activeTab].subheading}
                            </h3>
                            <p className="text-[#151515E5] text-medium-gray text-[14px] sm:text-base sm:leading-[24px]">
                                {tabContent[activeTab].description}
                            </p>
                            <ul className="space-y-2 sm:space-y-3">
                                {tabContent[activeTab].features.map((feature, index) => (
                                    <li key={index} className="list-disc ml-5">
                                        <span className="w-1.5 h-1.5 rounded-full bg-[#151515E5] " />
                                        <span className="text-[#151515E5] font-medium text-[14px] sm:text-base sm:leading-[29px]">{feature}</span>
                                    </li>
                                ))}
                            </ul>
                        </div>
                        <div className="relative h-[400px] rounded-lg overflow-hidden">
                            <Image
                                src={tabContent[activeTab].image || "/placeholder.svg"}
                                alt={`${tabContent[activeTab].title} using the AI detector`}
                                fill
                                className="object-cover transition-opacity rounded-[20px] duration-300"
                                sizes="(max-width: 768px) 100vw, 50vw"
                                priority
                            />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default OurAIDetectorIsPerfectFor

